name: Build and Release

on:
  push:
    tags:
      - '0*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script
        run: |
          python build.py

      - name: Upload artifacts for distribution
        uses: actions/upload-artifact@v4
        with:
          name: ReflowOven_${{ matrix.os }}
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect all artifacts for distribution
        uses: actions/download-artifact@v4

      - name: Zip up Windows artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ReflowOven_windows-latest.zip ReflowOven_windows-latest

      - name: Zip up Ubuntu artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ReflowOven_ubuntu-latest.zip ReflowOven_ubuntu-latest

      - name: Get release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: vX.X.X

      - name: Release artifacts with specified tag
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            ReflowOven_windows-latest.zip
            ReflowOven_ubuntu-latest.zip
